version: '3.8'
services:
  dev-db:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hey-blossom
    networks:
      - hey-blossom-net
networks:
  hey-blossom-net: