server:
  port: 8080

spring:
  application:
    name: hey_blossom_2024
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hey-blossom
    username: root
    password: 1234
  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update